title: Análise Cartola FC
email: analisecartolafc@gmail.com
url: https://cristianogoncalves.github.io/site
twitter: AnaliseCartola
description: análise estatística do cartola fc, calculo de probabilidades da pontuação dos jogadores a cada rodada.
google_analytics:
theme: soccer,futebol, cartola fc, estatística, probabilidade, brasileirão, série A